# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
import baml_py

from . import stream_types, types, type_builder
from .parser import LlmResponseParser, LlmStreamParser
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions
from .globals import DO_NOT_USE_DIRECTLY_UNLESS_YOU_KNOW_WHAT_YOURE_DOING_RUNTIME as __runtime__


class BamlAsyncClient:
    __options: DoNotUseDirectlyCallManager
    __stream_client: "BamlStreamClient"
    __http_request: "BamlHttpRequestClient"
    __http_stream_request: "BamlHttpStreamRequestClient"
    __llm_response_parser: LlmResponseParser
    __llm_stream_parser: LlmStreamParser

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options
        self.__stream_client = BamlStreamClient(options)
        self.__http_request = BamlHttpRequestClient(options)
        self.__http_stream_request = BamlHttpStreamRequestClient(options)
        self.__llm_response_parser = LlmResponseParser(options)
        self.__llm_stream_parser = LlmStreamParser(options)

    def with_options(self,
        tb: typing.Optional[type_builder.TypeBuilder] = None,
        client_registry: typing.Optional[baml_py.baml_py.ClientRegistry] = None,
        client: typing.Optional[str] = None,
        collector: typing.Optional[typing.Union[baml_py.baml_py.Collector, typing.List[baml_py.baml_py.Collector]]] = None,
        env: typing.Optional[typing.Dict[str, typing.Optional[str]]] = None,
        tags: typing.Optional[typing.Dict[str, str]] = None,
        on_tick: typing.Optional[typing.Callable[[str, baml_py.baml_py.FunctionLog], None]] = None,
    ) -> "BamlAsyncClient":
        options: BamlCallOptions = {}
        if tb is not None:
            options["tb"] = tb
        if client_registry is not None:
            options["client_registry"] = client_registry
        if client is not None:
            options["client"] = client
        if collector is not None:
            options["collector"] = collector
        if env is not None:
            options["env"] = env
        if tags is not None:
            options["tags"] = tags
        if on_tick is not None:
            options["on_tick"] = on_tick
        return BamlAsyncClient(self.__options.merge_options(options))

    @property
    def stream(self):
      return self.__stream_client

    @property
    def request(self):
      return self.__http_request

    @property
    def stream_request(self):
      return self.__http_stream_request

    @property
    def parse(self):
      return self.__llm_response_parser

    @property
    def parse_stream(self):
      return self.__llm_stream_parser

    async def AnalyzeVerifierOutput(self, command: str,exit_code: int,stdout: str,stderr: str,
        baml_options: BamlCallOptions = {},
    ) -> types.VerifierOutcome:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.AnalyzeVerifierOutput(command=command,exit_code=exit_code,stdout=stdout,stderr=stderr,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="AnalyzeVerifierOutput", args={
                "command": command,"exit_code": exit_code,"stdout": stdout,"stderr": stderr,
            })
            return typing.cast(types.VerifierOutcome, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def AssessTask(self, prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> types.TaskAssessment:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.AssessTask(prompt=prompt,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="AssessTask", args={
                "prompt": prompt,
            })
            return typing.cast(types.TaskAssessment, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def PlanAction(self, user_prompt: str,system_context: str,available_tools: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AgentPlan:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.PlanAction(user_prompt=user_prompt,system_context=system_context,available_tools=available_tools,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="PlanAction", args={
                "user_prompt": user_prompt,"system_context": system_context,"available_tools": available_tools,
            })
            return typing.cast(types.AgentPlan, __result__.cast_to(types, types, stream_types, False, __runtime__))
    async def SynthesizeResponse(self, user_prompt: str,tool_results: str,
        baml_options: BamlCallOptions = {},
    ) -> types.AgentResponse:
        # Check if on_tick is provided
        if 'on_tick' in baml_options:
            # Use streaming internally when on_tick is provided
            __stream__ = self.stream.SynthesizeResponse(user_prompt=user_prompt,tool_results=tool_results,
                baml_options=baml_options)
            return await __stream__.get_final_response()
        else:
            # Original non-streaming code
            __result__ = await self.__options.merge_options(baml_options).call_function_async(function_name="SynthesizeResponse", args={
                "user_prompt": user_prompt,"tool_results": tool_results,
            })
            return typing.cast(types.AgentResponse, __result__.cast_to(types, types, stream_types, False, __runtime__))
    


class BamlStreamClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeVerifierOutput(self, command: str,exit_code: int,stdout: str,stderr: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.VerifierOutcome, types.VerifierOutcome]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="AnalyzeVerifierOutput", args={
            "command": command,"exit_code": exit_code,"stdout": stdout,"stderr": stderr,
        })
        return baml_py.BamlStream[stream_types.VerifierOutcome, types.VerifierOutcome](
          __result__,
          lambda x: typing.cast(stream_types.VerifierOutcome, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.VerifierOutcome, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def AssessTask(self, prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.TaskAssessment, types.TaskAssessment]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="AssessTask", args={
            "prompt": prompt,
        })
        return baml_py.BamlStream[stream_types.TaskAssessment, types.TaskAssessment](
          __result__,
          lambda x: typing.cast(stream_types.TaskAssessment, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.TaskAssessment, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def PlanAction(self, user_prompt: str,system_context: str,available_tools: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.AgentPlan, types.AgentPlan]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="PlanAction", args={
            "user_prompt": user_prompt,"system_context": system_context,"available_tools": available_tools,
        })
        return baml_py.BamlStream[stream_types.AgentPlan, types.AgentPlan](
          __result__,
          lambda x: typing.cast(stream_types.AgentPlan, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AgentPlan, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    def SynthesizeResponse(self, user_prompt: str,tool_results: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.BamlStream[stream_types.AgentResponse, types.AgentResponse]:
        __ctx__, __result__ = self.__options.merge_options(baml_options).create_async_stream(function_name="SynthesizeResponse", args={
            "user_prompt": user_prompt,"tool_results": tool_results,
        })
        return baml_py.BamlStream[stream_types.AgentResponse, types.AgentResponse](
          __result__,
          lambda x: typing.cast(stream_types.AgentResponse, x.cast_to(types, types, stream_types, True, __runtime__)),
          lambda x: typing.cast(types.AgentResponse, x.cast_to(types, types, stream_types, False, __runtime__)),
          __ctx__,
        )
    

class BamlHttpRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AnalyzeVerifierOutput(self, command: str,exit_code: int,stdout: str,stderr: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AnalyzeVerifierOutput", args={
            "command": command,"exit_code": exit_code,"stdout": stdout,"stderr": stderr,
        }, mode="request")
        return __result__
    async def AssessTask(self, prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AssessTask", args={
            "prompt": prompt,
        }, mode="request")
        return __result__
    async def PlanAction(self, user_prompt: str,system_context: str,available_tools: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="PlanAction", args={
            "user_prompt": user_prompt,"system_context": system_context,"available_tools": available_tools,
        }, mode="request")
        return __result__
    async def SynthesizeResponse(self, user_prompt: str,tool_results: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SynthesizeResponse", args={
            "user_prompt": user_prompt,"tool_results": tool_results,
        }, mode="request")
        return __result__
    

class BamlHttpStreamRequestClient:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    async def AnalyzeVerifierOutput(self, command: str,exit_code: int,stdout: str,stderr: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AnalyzeVerifierOutput", args={
            "command": command,"exit_code": exit_code,"stdout": stdout,"stderr": stderr,
        }, mode="stream")
        return __result__
    async def AssessTask(self, prompt: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="AssessTask", args={
            "prompt": prompt,
        }, mode="stream")
        return __result__
    async def PlanAction(self, user_prompt: str,system_context: str,available_tools: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="PlanAction", args={
            "user_prompt": user_prompt,"system_context": system_context,"available_tools": available_tools,
        }, mode="stream")
        return __result__
    async def SynthesizeResponse(self, user_prompt: str,tool_results: str,
        baml_options: BamlCallOptions = {},
    ) -> baml_py.baml_py.HTTPRequest:
        __result__ = await self.__options.merge_options(baml_options).create_http_request_async(function_name="SynthesizeResponse", args={
            "user_prompt": user_prompt,"tool_results": tool_results,
        }, mode="stream")
        return __result__
    

b = BamlAsyncClient(DoNotUseDirectlyCallManager({}))