# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

_file_map = {

    "verifier.baml": "\ngenerator PythonClient {\n  output_type python/pydantic\n  output_dir \"../supervisor\"\n  version \"0.217.0\"\n}\n\nclass VerifierOutcome {\n  status string @description(\"One of: PASS, FAIL, BLOCKER\")\n  summary string @description(\"Concise summary of what happened\")\n  details string[] @description(\"Key observations or errors found in the logs\")\n  confidence float @description(\"0.0 to 1.0 confidence in this assessment\")\n}\n\nfunction AnalyzeVerifierOutput(command: string, exit_code: int, stdout: string, stderr: string) -> VerifierOutcome {\n  client GPT4o\n  prompt #\"\n    Analyze the execution of the following command:\n    Command: {{ command }}\n    Exit Code: {{ exit_code }}\n\n    --- STDOUT ---\n    {{ stdout }}\n\n    --- STDERR ---\n    {{ stderr }}\n\n    Determine if this was a success or failure.\n    Even if exit_code is 0, look for error messages in the logs.\n    If exit_code is non-zero, it is likely a failure, but explain why.\n\n    {{ ctx.output_format }}\n  \"#\n}\n\nclient<llm> GPT4o {\n  provider openai\n  options {\n    model \"gpt-4o\"\n    api_key env.OPENAI_API_KEY\n  }\n}\n",
}

def get_baml_files():
    return _file_map