# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions

import baml_py

from . import stream_types, types
from .runtime import DoNotUseDirectlyCallManager, BamlCallOptions

class LlmResponseParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeVerifierOutput(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.VerifierOutcome:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeVerifierOutput", llm_response=llm_response, mode="request")
        return typing.cast(types.VerifierOutcome, __result__)

    def AssessTask(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.TaskAssessment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AssessTask", llm_response=llm_response, mode="request")
        return typing.cast(types.TaskAssessment, __result__)

    def Audit(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AuditResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="Audit", llm_response=llm_response, mode="request")
        return typing.cast(types.AuditResult, __result__)

    def PlanAction(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AgentPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PlanAction", llm_response=llm_response, mode="request")
        return typing.cast(types.AgentPlan, __result__)

    def SynthesizeResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> types.AgentResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeResponse", llm_response=llm_response, mode="request")
        return typing.cast(types.AgentResponse, __result__)

    

class LlmStreamParser:
    __options: DoNotUseDirectlyCallManager

    def __init__(self, options: DoNotUseDirectlyCallManager):
        self.__options = options

    def AnalyzeVerifierOutput(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.VerifierOutcome:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AnalyzeVerifierOutput", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.VerifierOutcome, __result__)

    def AssessTask(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.TaskAssessment:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="AssessTask", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.TaskAssessment, __result__)

    def Audit(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AuditResult:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="Audit", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AuditResult, __result__)

    def PlanAction(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AgentPlan:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="PlanAction", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AgentPlan, __result__)

    def SynthesizeResponse(
        self, llm_response: str, baml_options: BamlCallOptions = {},
    ) -> stream_types.AgentResponse:
        __result__ = self.__options.merge_options(baml_options).parse_response(function_name="SynthesizeResponse", llm_response=llm_response, mode="stream")
        return typing.cast(stream_types.AgentResponse, __result__)

    