# ----------------------------------------------------------------------------
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ pip install baml
#
# ----------------------------------------------------------------------------

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code using: baml-cli generate
# baml-cli is available with the baml package.

import typing
import typing_extensions
from pydantic import BaseModel, ConfigDict, Field

import baml_py

from . import types

StreamStateValueT = typing.TypeVar('StreamStateValueT')
class StreamState(BaseModel, typing.Generic[StreamStateValueT]):
    value: StreamStateValueT
    state: typing_extensions.Literal["Pending", "Incomplete", "Complete"]
# #########################################################################
# Generated classes (1)
# #########################################################################

class VerifierOutcome(BaseModel):
    status: typing.Optional[str] = Field(default=None, description='One of: PASS, FAIL, BLOCKER')
    summary: typing.Optional[str] = Field(default=None, description='Concise summary of what happened')
    details: typing.List[str] = Field(description='Key observations or errors found in the logs')
    confidence: typing.Optional[float] = Field(default=None, description='0.0 to 1.0 confidence in this assessment')

# #########################################################################
# Generated type aliases (0)
# #########################################################################
